// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProbuf.proto

package com.cwa.prototype.protobuf;

public final class UserProbuf {
  private UserProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserIconOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 keyId = 1;
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 头像id
     * </pre>
     */
    boolean hasKeyId();
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 头像id
     * </pre>
     */
    int getKeyId();

    // required string desc = 2;
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    java.lang.String getDesc();
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    // required string conditionsDesc = 3;
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    boolean hasConditionsDesc();
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    java.lang.String getConditionsDesc();
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    com.google.protobuf.ByteString
        getConditionsDescBytes();

    // required int32 requireMoneyType = 4;
    /**
     * <code>required int32 requireMoneyType = 4;</code>
     *
     * <pre>
     * 所需货币类型
     * </pre>
     */
    boolean hasRequireMoneyType();
    /**
     * <code>required int32 requireMoneyType = 4;</code>
     *
     * <pre>
     * 所需货币类型
     * </pre>
     */
    int getRequireMoneyType();

    // required int32 requireMoneyCount = 5;
    /**
     * <code>required int32 requireMoneyCount = 5;</code>
     *
     * <pre>
     * 所需货币个数
     * </pre>
     */
    boolean hasRequireMoneyCount();
    /**
     * <code>required int32 requireMoneyCount = 5;</code>
     *
     * <pre>
     * 所需货币个数
     * </pre>
     */
    int getRequireMoneyCount();

    // required int32 condition = 6;
    /**
     * <code>required int32 condition = 6;</code>
     *
     * <pre>
     * 条件
     * </pre>
     */
    boolean hasCondition();
    /**
     * <code>required int32 condition = 6;</code>
     *
     * <pre>
     * 条件
     * </pre>
     */
    int getCondition();

    // repeated string conditionParamList = 7;
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    java.util.List<java.lang.String>
    getConditionParamListList();
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    int getConditionParamListCount();
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    java.lang.String getConditionParamList(int index);
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    com.google.protobuf.ByteString
        getConditionParamListBytes(int index);

    // required string iconFilename = 8;
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    boolean hasIconFilename();
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    java.lang.String getIconFilename();
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getIconFilenameBytes();
  }
  /**
   * Protobuf type {@code UserIcon}
   */
  public static final class UserIcon extends
      com.google.protobuf.GeneratedMessage
      implements UserIconOrBuilder {
    // Use UserIcon.newBuilder() to construct.
    private UserIcon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserIcon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserIcon defaultInstance;
    public static UserIcon getDefaultInstance() {
      return defaultInstance;
    }

    public UserIcon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserIcon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keyId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              desc_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              conditionsDesc_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              requireMoneyType_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              requireMoneyCount_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              condition_ = input.readInt32();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                conditionParamList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              conditionParamList_.add(input.readBytes());
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              iconFilename_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          conditionParamList_ = new com.google.protobuf.UnmodifiableLazyStringList(conditionParamList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserIcon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserIcon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.prototype.protobuf.UserProbuf.UserIcon.class, com.cwa.prototype.protobuf.UserProbuf.UserIcon.Builder.class);
    }

    public static com.google.protobuf.Parser<UserIcon> PARSER =
        new com.google.protobuf.AbstractParser<UserIcon>() {
      public UserIcon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserIcon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserIcon> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 keyId = 1;
    public static final int KEYID_FIELD_NUMBER = 1;
    private int keyId_;
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 头像id
     * </pre>
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 头像id
     * </pre>
     */
    public int getKeyId() {
      return keyId_;
    }

    // required string desc = 2;
    public static final int DESC_FIELD_NUMBER = 2;
    private java.lang.Object desc_;
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          desc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string desc = 2;</code>
     *
     * <pre>
     * 头像说明
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string conditionsDesc = 3;
    public static final int CONDITIONSDESC_FIELD_NUMBER = 3;
    private java.lang.Object conditionsDesc_;
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    public boolean hasConditionsDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    public java.lang.String getConditionsDesc() {
      java.lang.Object ref = conditionsDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          conditionsDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string conditionsDesc = 3;</code>
     *
     * <pre>
     * 解锁条件
     * </pre>
     */
    public com.google.protobuf.ByteString
        getConditionsDescBytes() {
      java.lang.Object ref = conditionsDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conditionsDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 requireMoneyType = 4;
    public static final int REQUIREMONEYTYPE_FIELD_NUMBER = 4;
    private int requireMoneyType_;
    /**
     * <code>required int32 requireMoneyType = 4;</code>
     *
     * <pre>
     * 所需货币类型
     * </pre>
     */
    public boolean hasRequireMoneyType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 requireMoneyType = 4;</code>
     *
     * <pre>
     * 所需货币类型
     * </pre>
     */
    public int getRequireMoneyType() {
      return requireMoneyType_;
    }

    // required int32 requireMoneyCount = 5;
    public static final int REQUIREMONEYCOUNT_FIELD_NUMBER = 5;
    private int requireMoneyCount_;
    /**
     * <code>required int32 requireMoneyCount = 5;</code>
     *
     * <pre>
     * 所需货币个数
     * </pre>
     */
    public boolean hasRequireMoneyCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 requireMoneyCount = 5;</code>
     *
     * <pre>
     * 所需货币个数
     * </pre>
     */
    public int getRequireMoneyCount() {
      return requireMoneyCount_;
    }

    // required int32 condition = 6;
    public static final int CONDITION_FIELD_NUMBER = 6;
    private int condition_;
    /**
     * <code>required int32 condition = 6;</code>
     *
     * <pre>
     * 条件
     * </pre>
     */
    public boolean hasCondition() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 condition = 6;</code>
     *
     * <pre>
     * 条件
     * </pre>
     */
    public int getCondition() {
      return condition_;
    }

    // repeated string conditionParamList = 7;
    public static final int CONDITIONPARAMLIST_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList conditionParamList_;
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    public java.util.List<java.lang.String>
        getConditionParamListList() {
      return conditionParamList_;
    }
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    public int getConditionParamListCount() {
      return conditionParamList_.size();
    }
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    public java.lang.String getConditionParamList(int index) {
      return conditionParamList_.get(index);
    }
    /**
     * <code>repeated string conditionParamList = 7;</code>
     *
     * <pre>
     * 任务条件参数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getConditionParamListBytes(int index) {
      return conditionParamList_.getByteString(index);
    }

    // required string iconFilename = 8;
    public static final int ICONFILENAME_FIELD_NUMBER = 8;
    private java.lang.Object iconFilename_;
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    public boolean hasIconFilename() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    public java.lang.String getIconFilename() {
      java.lang.Object ref = iconFilename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          iconFilename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string iconFilename = 8;</code>
     *
     * <pre>
     * 图片名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconFilenameBytes() {
      java.lang.Object ref = iconFilename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconFilename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      keyId_ = 0;
      desc_ = "";
      conditionsDesc_ = "";
      requireMoneyType_ = 0;
      requireMoneyCount_ = 0;
      condition_ = 0;
      conditionParamList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      iconFilename_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKeyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConditionsDesc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequireMoneyType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequireMoneyCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCondition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIconFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getConditionsDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, requireMoneyType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, requireMoneyCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, condition_);
      }
      for (int i = 0; i < conditionParamList_.size(); i++) {
        output.writeBytes(7, conditionParamList_.getByteString(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getIconFilenameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getConditionsDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, requireMoneyType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, requireMoneyCount_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, condition_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < conditionParamList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(conditionParamList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getConditionParamListList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getIconFilenameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserIcon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.prototype.protobuf.UserProbuf.UserIcon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserIcon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.prototype.protobuf.UserProbuf.UserIconOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserIcon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserIcon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.prototype.protobuf.UserProbuf.UserIcon.class, com.cwa.prototype.protobuf.UserProbuf.UserIcon.Builder.class);
      }

      // Construct using com.cwa.prototype.protobuf.UserProbuf.UserIcon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        conditionsDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        requireMoneyType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        requireMoneyCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        condition_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        conditionParamList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        iconFilename_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserIcon_descriptor;
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserIcon getDefaultInstanceForType() {
        return com.cwa.prototype.protobuf.UserProbuf.UserIcon.getDefaultInstance();
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserIcon build() {
        com.cwa.prototype.protobuf.UserProbuf.UserIcon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserIcon buildPartial() {
        com.cwa.prototype.protobuf.UserProbuf.UserIcon result = new com.cwa.prototype.protobuf.UserProbuf.UserIcon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyId_ = keyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.conditionsDesc_ = conditionsDesc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requireMoneyType_ = requireMoneyType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requireMoneyCount_ = requireMoneyCount_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.condition_ = condition_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          conditionParamList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              conditionParamList_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.conditionParamList_ = conditionParamList_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.iconFilename_ = iconFilename_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.prototype.protobuf.UserProbuf.UserIcon) {
          return mergeFrom((com.cwa.prototype.protobuf.UserProbuf.UserIcon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.prototype.protobuf.UserProbuf.UserIcon other) {
        if (other == com.cwa.prototype.protobuf.UserProbuf.UserIcon.getDefaultInstance()) return this;
        if (other.hasKeyId()) {
          setKeyId(other.getKeyId());
        }
        if (other.hasDesc()) {
          bitField0_ |= 0x00000002;
          desc_ = other.desc_;
          onChanged();
        }
        if (other.hasConditionsDesc()) {
          bitField0_ |= 0x00000004;
          conditionsDesc_ = other.conditionsDesc_;
          onChanged();
        }
        if (other.hasRequireMoneyType()) {
          setRequireMoneyType(other.getRequireMoneyType());
        }
        if (other.hasRequireMoneyCount()) {
          setRequireMoneyCount(other.getRequireMoneyCount());
        }
        if (other.hasCondition()) {
          setCondition(other.getCondition());
        }
        if (!other.conditionParamList_.isEmpty()) {
          if (conditionParamList_.isEmpty()) {
            conditionParamList_ = other.conditionParamList_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureConditionParamListIsMutable();
            conditionParamList_.addAll(other.conditionParamList_);
          }
          onChanged();
        }
        if (other.hasIconFilename()) {
          bitField0_ |= 0x00000080;
          iconFilename_ = other.iconFilename_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKeyId()) {
          
          return false;
        }
        if (!hasDesc()) {
          
          return false;
        }
        if (!hasConditionsDesc()) {
          
          return false;
        }
        if (!hasRequireMoneyType()) {
          
          return false;
        }
        if (!hasRequireMoneyCount()) {
          
          return false;
        }
        if (!hasCondition()) {
          
          return false;
        }
        if (!hasIconFilename()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.prototype.protobuf.UserProbuf.UserIcon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.prototype.protobuf.UserProbuf.UserIcon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 keyId = 1;
      private int keyId_ ;
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 头像id
       * </pre>
       */
      public boolean hasKeyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 头像id
       * </pre>
       */
      public int getKeyId() {
        return keyId_;
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 头像id
       * </pre>
       */
      public Builder setKeyId(int value) {
        bitField0_ |= 0x00000001;
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 头像id
       * </pre>
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyId_ = 0;
        onChanged();
        return this;
      }

      // required string desc = 2;
      private java.lang.Object desc_ = "";
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string desc = 2;</code>
       *
       * <pre>
       * 头像说明
       * </pre>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        desc_ = value;
        onChanged();
        return this;
      }

      // required string conditionsDesc = 3;
      private java.lang.Object conditionsDesc_ = "";
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public boolean hasConditionsDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public java.lang.String getConditionsDesc() {
        java.lang.Object ref = conditionsDesc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          conditionsDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public com.google.protobuf.ByteString
          getConditionsDescBytes() {
        java.lang.Object ref = conditionsDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          conditionsDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public Builder setConditionsDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        conditionsDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public Builder clearConditionsDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        conditionsDesc_ = getDefaultInstance().getConditionsDesc();
        onChanged();
        return this;
      }
      /**
       * <code>required string conditionsDesc = 3;</code>
       *
       * <pre>
       * 解锁条件
       * </pre>
       */
      public Builder setConditionsDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        conditionsDesc_ = value;
        onChanged();
        return this;
      }

      // required int32 requireMoneyType = 4;
      private int requireMoneyType_ ;
      /**
       * <code>required int32 requireMoneyType = 4;</code>
       *
       * <pre>
       * 所需货币类型
       * </pre>
       */
      public boolean hasRequireMoneyType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 requireMoneyType = 4;</code>
       *
       * <pre>
       * 所需货币类型
       * </pre>
       */
      public int getRequireMoneyType() {
        return requireMoneyType_;
      }
      /**
       * <code>required int32 requireMoneyType = 4;</code>
       *
       * <pre>
       * 所需货币类型
       * </pre>
       */
      public Builder setRequireMoneyType(int value) {
        bitField0_ |= 0x00000008;
        requireMoneyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requireMoneyType = 4;</code>
       *
       * <pre>
       * 所需货币类型
       * </pre>
       */
      public Builder clearRequireMoneyType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requireMoneyType_ = 0;
        onChanged();
        return this;
      }

      // required int32 requireMoneyCount = 5;
      private int requireMoneyCount_ ;
      /**
       * <code>required int32 requireMoneyCount = 5;</code>
       *
       * <pre>
       * 所需货币个数
       * </pre>
       */
      public boolean hasRequireMoneyCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 requireMoneyCount = 5;</code>
       *
       * <pre>
       * 所需货币个数
       * </pre>
       */
      public int getRequireMoneyCount() {
        return requireMoneyCount_;
      }
      /**
       * <code>required int32 requireMoneyCount = 5;</code>
       *
       * <pre>
       * 所需货币个数
       * </pre>
       */
      public Builder setRequireMoneyCount(int value) {
        bitField0_ |= 0x00000010;
        requireMoneyCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requireMoneyCount = 5;</code>
       *
       * <pre>
       * 所需货币个数
       * </pre>
       */
      public Builder clearRequireMoneyCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requireMoneyCount_ = 0;
        onChanged();
        return this;
      }

      // required int32 condition = 6;
      private int condition_ ;
      /**
       * <code>required int32 condition = 6;</code>
       *
       * <pre>
       * 条件
       * </pre>
       */
      public boolean hasCondition() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 condition = 6;</code>
       *
       * <pre>
       * 条件
       * </pre>
       */
      public int getCondition() {
        return condition_;
      }
      /**
       * <code>required int32 condition = 6;</code>
       *
       * <pre>
       * 条件
       * </pre>
       */
      public Builder setCondition(int value) {
        bitField0_ |= 0x00000020;
        condition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 condition = 6;</code>
       *
       * <pre>
       * 条件
       * </pre>
       */
      public Builder clearCondition() {
        bitField0_ = (bitField0_ & ~0x00000020);
        condition_ = 0;
        onChanged();
        return this;
      }

      // repeated string conditionParamList = 7;
      private com.google.protobuf.LazyStringList conditionParamList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureConditionParamListIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          conditionParamList_ = new com.google.protobuf.LazyStringArrayList(conditionParamList_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public java.util.List<java.lang.String>
          getConditionParamListList() {
        return java.util.Collections.unmodifiableList(conditionParamList_);
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public int getConditionParamListCount() {
        return conditionParamList_.size();
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public java.lang.String getConditionParamList(int index) {
        return conditionParamList_.get(index);
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getConditionParamListBytes(int index) {
        return conditionParamList_.getByteString(index);
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public Builder setConditionParamList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureConditionParamListIsMutable();
        conditionParamList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public Builder addConditionParamList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureConditionParamListIsMutable();
        conditionParamList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public Builder addAllConditionParamList(
          java.lang.Iterable<java.lang.String> values) {
        ensureConditionParamListIsMutable();
        super.addAll(values, conditionParamList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public Builder clearConditionParamList() {
        conditionParamList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string conditionParamList = 7;</code>
       *
       * <pre>
       * 任务条件参数
       * </pre>
       */
      public Builder addConditionParamListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureConditionParamListIsMutable();
        conditionParamList_.add(value);
        onChanged();
        return this;
      }

      // required string iconFilename = 8;
      private java.lang.Object iconFilename_ = "";
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public boolean hasIconFilename() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public java.lang.String getIconFilename() {
        java.lang.Object ref = iconFilename_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          iconFilename_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIconFilenameBytes() {
        java.lang.Object ref = iconFilename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconFilename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public Builder setIconFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        iconFilename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public Builder clearIconFilename() {
        bitField0_ = (bitField0_ & ~0x00000080);
        iconFilename_ = getDefaultInstance().getIconFilename();
        onChanged();
        return this;
      }
      /**
       * <code>required string iconFilename = 8;</code>
       *
       * <pre>
       * 图片名称
       * </pre>
       */
      public Builder setIconFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        iconFilename_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserIcon)
    }

    static {
      defaultInstance = new UserIcon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UserIcon)
  }

  public interface UserLevelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 keyId = 1;
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 家园等级
     * </pre>
     */
    boolean hasKeyId();
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 家园等级
     * </pre>
     */
    int getKeyId();

    // required int32 experience = 2;
    /**
     * <code>required int32 experience = 2;</code>
     *
     * <pre>
     * 经验
     * </pre>
     */
    boolean hasExperience();
    /**
     * <code>required int32 experience = 2;</code>
     *
     * <pre>
     * 经验
     * </pre>
     */
    int getExperience();

    // required int32 experienceCount = 3;
    /**
     * <code>required int32 experienceCount = 3;</code>
     *
     * <pre>
     * 累积经验
     * </pre>
     */
    boolean hasExperienceCount();
    /**
     * <code>required int32 experienceCount = 3;</code>
     *
     * <pre>
     * 累积经验
     * </pre>
     */
    int getExperienceCount();

    // required int32 powerMax = 4;
    /**
     * <code>required int32 powerMax = 4;</code>
     *
     * <pre>
     * 体力上限
     * </pre>
     */
    boolean hasPowerMax();
    /**
     * <code>required int32 powerMax = 4;</code>
     *
     * <pre>
     * 体力上限
     * </pre>
     */
    int getPowerMax();
  }
  /**
   * Protobuf type {@code UserLevel}
   */
  public static final class UserLevel extends
      com.google.protobuf.GeneratedMessage
      implements UserLevelOrBuilder {
    // Use UserLevel.newBuilder() to construct.
    private UserLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserLevel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserLevel defaultInstance;
    public static UserLevel getDefaultInstance() {
      return defaultInstance;
    }

    public UserLevel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              keyId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              experience_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              experienceCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              powerMax_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserLevel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cwa.prototype.protobuf.UserProbuf.UserLevel.class, com.cwa.prototype.protobuf.UserProbuf.UserLevel.Builder.class);
    }

    public static com.google.protobuf.Parser<UserLevel> PARSER =
        new com.google.protobuf.AbstractParser<UserLevel>() {
      public UserLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserLevel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserLevel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 keyId = 1;
    public static final int KEYID_FIELD_NUMBER = 1;
    private int keyId_;
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 家园等级
     * </pre>
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 keyId = 1;</code>
     *
     * <pre>
     * 家园等级
     * </pre>
     */
    public int getKeyId() {
      return keyId_;
    }

    // required int32 experience = 2;
    public static final int EXPERIENCE_FIELD_NUMBER = 2;
    private int experience_;
    /**
     * <code>required int32 experience = 2;</code>
     *
     * <pre>
     * 经验
     * </pre>
     */
    public boolean hasExperience() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 experience = 2;</code>
     *
     * <pre>
     * 经验
     * </pre>
     */
    public int getExperience() {
      return experience_;
    }

    // required int32 experienceCount = 3;
    public static final int EXPERIENCECOUNT_FIELD_NUMBER = 3;
    private int experienceCount_;
    /**
     * <code>required int32 experienceCount = 3;</code>
     *
     * <pre>
     * 累积经验
     * </pre>
     */
    public boolean hasExperienceCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 experienceCount = 3;</code>
     *
     * <pre>
     * 累积经验
     * </pre>
     */
    public int getExperienceCount() {
      return experienceCount_;
    }

    // required int32 powerMax = 4;
    public static final int POWERMAX_FIELD_NUMBER = 4;
    private int powerMax_;
    /**
     * <code>required int32 powerMax = 4;</code>
     *
     * <pre>
     * 体力上限
     * </pre>
     */
    public boolean hasPowerMax() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 powerMax = 4;</code>
     *
     * <pre>
     * 体力上限
     * </pre>
     */
    public int getPowerMax() {
      return powerMax_;
    }

    private void initFields() {
      keyId_ = 0;
      experience_ = 0;
      experienceCount_ = 0;
      powerMax_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKeyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperience()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExperienceCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPowerMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, keyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, experience_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, experienceCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, powerMax_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, keyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, experience_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, experienceCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, powerMax_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cwa.prototype.protobuf.UserProbuf.UserLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cwa.prototype.protobuf.UserProbuf.UserLevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cwa.prototype.protobuf.UserProbuf.UserLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserLevel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cwa.prototype.protobuf.UserProbuf.UserLevel.class, com.cwa.prototype.protobuf.UserProbuf.UserLevel.Builder.class);
      }

      // Construct using com.cwa.prototype.protobuf.UserProbuf.UserLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        experience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        experienceCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        powerMax_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cwa.prototype.protobuf.UserProbuf.internal_static_UserLevel_descriptor;
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserLevel getDefaultInstanceForType() {
        return com.cwa.prototype.protobuf.UserProbuf.UserLevel.getDefaultInstance();
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserLevel build() {
        com.cwa.prototype.protobuf.UserProbuf.UserLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cwa.prototype.protobuf.UserProbuf.UserLevel buildPartial() {
        com.cwa.prototype.protobuf.UserProbuf.UserLevel result = new com.cwa.prototype.protobuf.UserProbuf.UserLevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyId_ = keyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.experience_ = experience_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.experienceCount_ = experienceCount_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.powerMax_ = powerMax_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cwa.prototype.protobuf.UserProbuf.UserLevel) {
          return mergeFrom((com.cwa.prototype.protobuf.UserProbuf.UserLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cwa.prototype.protobuf.UserProbuf.UserLevel other) {
        if (other == com.cwa.prototype.protobuf.UserProbuf.UserLevel.getDefaultInstance()) return this;
        if (other.hasKeyId()) {
          setKeyId(other.getKeyId());
        }
        if (other.hasExperience()) {
          setExperience(other.getExperience());
        }
        if (other.hasExperienceCount()) {
          setExperienceCount(other.getExperienceCount());
        }
        if (other.hasPowerMax()) {
          setPowerMax(other.getPowerMax());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKeyId()) {
          
          return false;
        }
        if (!hasExperience()) {
          
          return false;
        }
        if (!hasExperienceCount()) {
          
          return false;
        }
        if (!hasPowerMax()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cwa.prototype.protobuf.UserProbuf.UserLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cwa.prototype.protobuf.UserProbuf.UserLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 keyId = 1;
      private int keyId_ ;
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 家园等级
       * </pre>
       */
      public boolean hasKeyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 家园等级
       * </pre>
       */
      public int getKeyId() {
        return keyId_;
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 家园等级
       * </pre>
       */
      public Builder setKeyId(int value) {
        bitField0_ |= 0x00000001;
        keyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 keyId = 1;</code>
       *
       * <pre>
       * 家园等级
       * </pre>
       */
      public Builder clearKeyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyId_ = 0;
        onChanged();
        return this;
      }

      // required int32 experience = 2;
      private int experience_ ;
      /**
       * <code>required int32 experience = 2;</code>
       *
       * <pre>
       * 经验
       * </pre>
       */
      public boolean hasExperience() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 experience = 2;</code>
       *
       * <pre>
       * 经验
       * </pre>
       */
      public int getExperience() {
        return experience_;
      }
      /**
       * <code>required int32 experience = 2;</code>
       *
       * <pre>
       * 经验
       * </pre>
       */
      public Builder setExperience(int value) {
        bitField0_ |= 0x00000002;
        experience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 experience = 2;</code>
       *
       * <pre>
       * 经验
       * </pre>
       */
      public Builder clearExperience() {
        bitField0_ = (bitField0_ & ~0x00000002);
        experience_ = 0;
        onChanged();
        return this;
      }

      // required int32 experienceCount = 3;
      private int experienceCount_ ;
      /**
       * <code>required int32 experienceCount = 3;</code>
       *
       * <pre>
       * 累积经验
       * </pre>
       */
      public boolean hasExperienceCount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 experienceCount = 3;</code>
       *
       * <pre>
       * 累积经验
       * </pre>
       */
      public int getExperienceCount() {
        return experienceCount_;
      }
      /**
       * <code>required int32 experienceCount = 3;</code>
       *
       * <pre>
       * 累积经验
       * </pre>
       */
      public Builder setExperienceCount(int value) {
        bitField0_ |= 0x00000004;
        experienceCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 experienceCount = 3;</code>
       *
       * <pre>
       * 累积经验
       * </pre>
       */
      public Builder clearExperienceCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        experienceCount_ = 0;
        onChanged();
        return this;
      }

      // required int32 powerMax = 4;
      private int powerMax_ ;
      /**
       * <code>required int32 powerMax = 4;</code>
       *
       * <pre>
       * 体力上限
       * </pre>
       */
      public boolean hasPowerMax() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 powerMax = 4;</code>
       *
       * <pre>
       * 体力上限
       * </pre>
       */
      public int getPowerMax() {
        return powerMax_;
      }
      /**
       * <code>required int32 powerMax = 4;</code>
       *
       * <pre>
       * 体力上限
       * </pre>
       */
      public Builder setPowerMax(int value) {
        bitField0_ |= 0x00000008;
        powerMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 powerMax = 4;</code>
       *
       * <pre>
       * 体力上限
       * </pre>
       */
      public Builder clearPowerMax() {
        bitField0_ = (bitField0_ & ~0x00000008);
        powerMax_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserLevel)
    }

    static {
      defaultInstance = new UserLevel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:UserLevel)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserIcon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserIcon_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserLevel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020UserProbuf.proto\"\271\001\n\010UserIcon\022\r\n\005keyId" +
      "\030\001 \002(\005\022\014\n\004desc\030\002 \002(\t\022\026\n\016conditionsDesc\030\003" +
      " \002(\t\022\030\n\020requireMoneyType\030\004 \002(\005\022\031\n\021requir" +
      "eMoneyCount\030\005 \002(\005\022\021\n\tcondition\030\006 \002(\005\022\032\n\022" +
      "conditionParamList\030\007 \003(\t\022\024\n\014iconFilename" +
      "\030\010 \002(\t\"Y\n\tUserLevel\022\r\n\005keyId\030\001 \002(\005\022\022\n\nex" +
      "perience\030\002 \002(\005\022\027\n\017experienceCount\030\003 \002(\005\022" +
      "\020\n\010powerMax\030\004 \002(\005B(\n\032com.cwa.prototype.p" +
      "rotobufB\nUserProbuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_UserIcon_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_UserIcon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserIcon_descriptor,
              new java.lang.String[] { "KeyId", "Desc", "ConditionsDesc", "RequireMoneyType", "RequireMoneyCount", "Condition", "ConditionParamList", "IconFilename", });
          internal_static_UserLevel_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_UserLevel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserLevel_descriptor,
              new java.lang.String[] { "KeyId", "Experience", "ExperienceCount", "PowerMax", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
